# -*- mode: python ; coding: utf-8 -*-
# Spec de PyInstaller — Launcher de Expediente Digital (onefile)
# Entry point: launcher_with_splash.py

a = Analysis(
    ["launcher_with_splash.py"],
    pathex=["."],
    binaries=[],
    datas=[],
    hiddenimports=[
        "launcher_main",
        "ctypes",
        "ctypes.wintypes",
        "urllib.request",
        "urllib.parse",
        "urllib.error",
        "json",
        "shutil",
        "subprocess",
        "threading",
        "time",
        "webbrowser",
        "pathlib",
        "datetime",
        "traceback",
        "tkinter",
        "tkinter.ttk",
        "_tkinter",
    ],
    hookspath=[],
    hooksconfig={},
    runtime_hooks=[],
    excludes=[
        "fastapi", "uvicorn", "starlette", "anyio", "aiofiles",
        "pydantic", "pydantic_core",
        "PIL", "Pillow", "pymupdf", "fitz",
        "reportlab", "docx", "lxml",
        "h11", "multipart", "python_multipart",
        "httpx", "httpcore", "requests",
        "numpy", "scipy", "matplotlib",
        "IPython", "jupyter",
        "pytest", "unittest", "doctest", "pdb",
        "multiprocessing",
        "asyncio",
        "xmlrpc",
    ],
    noarchive=False,
)

pyz = PYZ(a.pure)

exe = EXE(
    pyz,
    a.scripts,
    a.binaries,
    a.datas,
    exclude_binaries=False,
    name="ExpedienteDigital",
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx=True,
    upx_exclude=[],
    console=False,
    disable_windowed_traceback=False,
    argv_emulation=False,
    target_arch=None,
    codesign_identity=None,
    entitlements_file=None,
    icon="assets/icono.ico",
)
